# Generated by Django 3.1.1 on 2020-09-03 13:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sensordaten', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messwert',
            name='sensor_read_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
